src/Editionista/WebsiteBundle/Entity/Edition.php
<?php

namespace Editionista\WebsiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity
 * @ORM\Table(name="edition")
 */
class Edition
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Unique edition name
     *
     * @ORM\Column()
     */
    private $name;

    /**
     * @Gedmo\Slug(fields={"repository"}, style="default")
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;
    
    /**
     * Repository
     *
     * @ORM\Column()
     */
    private $repository;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="Version", inversedBy="editions")
     * @ORM\JoinColumn(name="version_id", referencedColumnName="id")
     */
    protected $version;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reference;

    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $homepage;

    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $readme;

    
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $travis;

    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $license;

    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $licenseType;

    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $packagist;

    /**
     * @ORM\ManyToMany(targetEntity="User", inversedBy="editions")
     * @ORM\JoinTable(name="users_editions")
     */
    private $users;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="editions", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedRepositoryAt;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->createdAt = new \DateTime;
    }

    /**
     * Get id
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Get vendor prefix
     *
     * @return string
     */
    public function getVendor()
    {
        return preg_replace('{/.*$}', '', $this->repository);
    }

    /**
     * Get edition name without vendor
     *
     * @return string
     */
    public function getEditionName()
    {
        return preg_replace('{^[^/]*/}', '', $this->repository);
    }

    /**
     * Set description
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set repository
     *
     * @param string $repository
     */
    public function setRepository($repository)
    {
        $this->repository = $repository;
    }

    /**
     * Get repository
     *
     * @return string $repository
     */
    public function getRepository()
    {
        return $this->repository;
    }

    /**
     * Add users
     *
     * @param \Packagist\WebBundle\Entity\User $user
     */
    public function addUser(User $user)
    {
        $this->users[] = $user;
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Remove users
     *
     * @param \Editionista\WebsiteBundle\Entity\User $users
     */
    public function removeUser(\Editionista\WebsiteBundle\Entity\User $users)
    {
        $this->users->removeElement($users);
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set reference
     *
     * @param string $reference
     * @return Edition
     */
    public function setReference($reference)
    {
        $this->reference = $reference;
    
        return $this;
    }

    /**
     * Get reference
     *
     * @return string 
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Set homepage
     *
     * @param string $homepage
     * @return Edition
     */
    public function setHomepage($homepage)
    {
        $this->homepage = $homepage;
    
        return $this;
    }

    /**
     * Get homepage
     *
     * @return string 
     */
    public function getHomepage()
    {
        return $this->homepage;
    }

    /**
     * Set readme
     *
     * @param string $readme
     * @return Edition
     */
    public function setReadme($readme)
    {
        $this->readme = $readme;
    
        return $this;
    }

    /**
     * Get readme
     *
     * @return string 
     */
    public function getReadme()
    {
        return $this->readme;
    }

    /**
     * Set travis
     *
     * @param string $travis
     * @return Edition
     */
    public function setTravis($travis)
    {
        $this->travis = $travis;
    
        return $this;
    }

    /**
     * Get travis
     *
     * @return string 
     */
    public function getTravis()
    {
        return $this->travis;
    }

    /**
     * Set license
     *
     * @param string $license
     * @return Edition
     */
    public function setLicense($license)
    {
        $this->license = $license;
    
        return $this;
    }

    /**
     * Get license
     *
     * @return string 
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * Set licenseType
     *
     * @param string $licenseType
     * @return Edition
     */
    public function setLicenseType($licenseType)
    {
        $this->licenseType = $licenseType;
    
        return $this;
    }

    /**
     * Get licenseType
     *
     * @return string 
     */
    public function getLicenseType()
    {
        return $this->licenseType;
    }

    /**
     * Set packagist
     *
     * @param string $packagist
     * @return Edition
     */
    public function setPackagist($packagist)
    {
        $this->packagist = $packagist;
    
        return $this;
    }

    /**
     * Get packagist
     *
     * @return string 
     */
    public function getPackagist()
    {
        return $this->packagist;
    }

    /**
     * Set updatedRepositoryAt
     *
     * @param \DateTime $updatedRepositoryAt
     * @return Edition
     */
    public function setUpdatedRepositoryAt($updatedRepositoryAt)
    {
        $this->updatedRepositoryAt = $updatedRepositoryAt;
    
        return $this;
    }

    /**
     * Get updatedRepositoryAt
     *
     * @return \DateTime 
     */
    public function getUpdatedRepositoryAt()
    {
        return $this->updatedRepositoryAt;
    }

    /**
     * Set version
     *
     * @param \Editionista\WebsiteBundle\Entity\Version $version
     * @return Edition
     */
    public function setVersion(\Editionista\WebsiteBundle\Entity\Version $version = null)
    {
        $this->version = $version;
    
        return $this;
    }

    /**
     * Get version
     *
     * @return \Editionista\WebsiteBundle\Entity\Version 
     */
    public function getVersion()
    {
        return $this->version;
    }
 
    /**
     * Set slug
     *
     * @param string $slug
     * @return Edition
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }
    
    public function addTag(Tag $tag)
    {
        if(!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }
    }

    public function setTags(array $tags)
    {
        $this->tags->clear();
        
        foreach($tags as $tag) {
            $this->addTag($tag);
        }
    }
    
    public function getTags()
    {
        return $this->tags;
    }
    
    /**
     * Remove users
     *
     * @param \Editionista\WebsiteBundle\Entity\Tag $tag
     */
    public function removeTag(\Editionista\WebsiteBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

}

src/Editionista/WebsiteBundle/Form/Type/EditionType.php
<?php

namespace Editionista\WebsiteBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EditionType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text',
                    array('label' => 'Edition name', 'attr' => array('placeholder' => 'Awesome Edition')))
            ->add('reference', 'text',
                    array('label' => 'Exact version or commit', 'required' => false,
                        'attr' => array('help_block' => '(Commit with version "dev-master")', 'placeholder' => 'f.e. "2.1.10" or "efabb1e"')))
            ->add('homepage', 'text',
                    array('required' => false,
                        'attr' => array('placeholder' => 'http://example.com')))
            ->add('readme', 'textarea',
                    array('required' => false,
                        'attr' => array('placeholder' => 'Markdown readme Information', 'rows'  => '12', 'class' => 'input-xxlarge')))
            ->add('license', 'textarea',
                    array('required' => false,
                        'attr' => array('placeholder' => 'License Information', 'rows'  => '10', 'class' => 'input-xxlarge')))
            ->add('licenseType', 'choice',
                    array('choices'   => array('other' => 'other', 'MIT' => 'MIT', 'BSD' => 'BSD', 'Apache' => 'Apache'), 'required' => true,
                        'attr' => array('placeholder' => 'License Type')))
            ->add('description', 'textarea',
                    array('required' => true,
                        'attr' => array('placeholder' => 'Short description', 'rows'  => '14', 'class' => 'input-xxlarge')))
            ->add('version', null, array('label' => 'Symfony2 version used', 'required' => true, 'attr' => array('help_block' => 'Symfony2 version this Edition is based on.')))
                
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Editionista\WebsiteBundle\Entity\Edition'
        ));
    }

    public function getName()
    {
        return 'editionista_websitebundle_editiontype';
    }
}

src/Editionista/WebsiteBundle/Resources/views/Edition/add.html.twig
{% extends "EditionistaWebsiteBundle::layout.html.twig" %}

{% block breadcrumbs %}
    <li><a href="{{ path('home') }}"><i class="icon-home"></i> Home</a> <span class="divider">/</span></li>
    <li><a href="{{ path('edition_add_list') }}">Submit an Edition</a> <span class="divider">/</span></li>
    <li class="active">{{ repo }}</li>
{% endblock %}
    
{% block javascript %}
<script>
    jQuery(".tagManager").tagsManager(
        {
            CapitalizeFirstLetter: true,
            preventSubmitOnEnter: true,
            //prefilled: ["Tags", "OnEdit"],
            typeahead: true,
            typeaheadAjaxPolling: true,
            typeaheadAjaxSource: '/tags/pull',
            AjaxPush: '/tags/push',
        }
    );

    if($("#editionista_websitebundle_editiontype_licenseType").val() !== 'other') {
        $("#editionista_websitebundle_editiontype_license").hide();
    }

    $('#editionista_websitebundle_editiontype_licenseType').on(
    'change',
        function() {
            if(this.value === 'other') {
                $('#editionista_websitebundle_editiontype_license').show();

            } else {
                $("#editionista_websitebundle_editiontype_license").hide();
            }
        }
    );
</script>
{% endblock %}

{% block content %}
    {% form_theme form with '::form.html.twig' %}
    
<div class="row-fluid">
    <div class="span12">
        <h1>Add <span class="muted">&ldquo;</span> {{ name }}/{{ repo }} <span class="muted">&rdquo; as an Edition</span></h1>
        <p>
             <small>Last Push: {% if last_push is not null %}{{ time_diff(last_push) }}{% else %}Unknown{% endif %}</small>
        </p>
    </div>
</div>
<form class="form-horizontal" action="{{ path('edition_add', { 'name': name, 'repo': repo }) }}" method="post" {{ form_enctype(form) }}>
<div class="row-fluid space">
    <div class="span3">
        <legend>General Information</legend>
        <p>
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
        </p>
        <p>
            {{ form_label(form.homepage) }}
            {{ form_widget(form.homepage) }}
        </p>
        <p>
            {{ form_label(form.version) }}
            {{ form_widget(form.version) }}
        </p>
        <p>
            {{ form_label(form.reference) }}
            {{ form_widget(form.reference) }}
        </p>
    </div>
    <div class="span3">
        <legend>Tags</legend>
            <label for="tags">Tags</label>
            <p><input type="text" name="tags" placeholder="Tags" class="tagManager"/></p>
    </div>
    <div class="span6">
        <legend>Description</legend>
        {{ form_widget(form.description) }}
    </div>
</div>
<div class="row-fluid space">
    <div class="span6">
        <legend>Readme</legend>
        <p>{{ form_widget(form.readme) }}</p>
    </div>
    <div class="span6">
        <legend>License</legend>        
        <p>{{ form_widget(form.licenseType) }}</p>
        <p>{{ form_widget(form.license) }}</p>
    </div>
</div>
<div class="row-fluid space">
    <div class="span12">
        {{ form_widget(form) }}
    </div>
</div>
<p>
    <button type="submit" class="btn"><i class="icon-ok"></i> Submit</button>
</p>

</form>

{% endblock %}

src/Editionista/WebsiteBundle/Resources/views/Edition/addList.html.twig
{% extends "EditionistaWebsiteBundle::layout.html.twig" %}

{% block breadcrumbs %}
    <li><a href="{{ path('home') }}"><i class="icon-home"></i> Home</a> <span class="divider">/</span></li>
    <li class="active">Submit an Edition</li>
{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h1>Submit Editions</h1>
        <p>
            Submit one of your Github repositories as a Symfony2 Edition.
        </p>
    </div>
</div>
{% if app.user %}
    {% for repository in repositories %}
        <div class="row-fluid fix-margin space">
            <div class="span12 well well-hover">
                <div class="span1">
                  {% if repository.exists is not defined %}
                    <p>
                        <a href="{{ path('edition_add', {'name': repository.owner.login, 'repo': repository.name }) }}" >
                            <i class="icon-plus icon-3x icon-muted icon-muted-hover" data-placement="left" rel="tooltip" data-original-title="Submit"></i>
                        </a>
                    </p>
                </div>
                <div class="span11">
                    <h2>{{ repository.name }} <small>({{ repository.full_name }})</small></h2>
                  {% else %}
                    <p>
                        <a href="{{ path('edition_edit', {'slug': repository.exists }) }}" >
                            <i class="icon-wrench icon-3x icon-muted icon-muted-hover" data-placement="left" rel="tooltip" data-original-title="Edit"></i>
                        </a>
                    </p>
                </div>
                <div class="span11">
                    <h2><a href="{{ path('edition_show', { 'slug': repository.exists }) }}">{{ repository.name }}</a> <small>({{ repository.full_name }}) <i class="icon-ok icon-muted" data-placement="right" rel="tooltip" data-original-title="Edition has been submitted"></i> </small></h2>
                  {% endif %}
                    <p>
                        <small>Last updated: {{ time_diff(repository.pushed_at) }}, Repository: <a href="{{ repository.html_url }}">{{ repository.git_url }}</a></small>
                    </p>
                    {% if repository.description|length %}
                        <br />
                        <strong>Description</strong>
                        <p>{{ repository.description }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="row-fluid fix-margin space">
            <div class="span12 well">
                <p>Could not fetch any repositories from Github.</p>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="row-fluid fix-margin space">
        <div class="span12 well">
            <p>Not logged in.</p>
        </div>
    </div>
{% endif %}

{% endblock %}

src/Editionista/WebsiteBundle/Resources/views/Edition/edit.html.twig
{% extends "EditionistaWebsiteBundle::layout.html.twig" %}

{% block breadcrumbs %}
    <li><a href="{{ path('home') }}"><i class="icon-home"></i> Home</a> <span class="divider">/</span></li>
    <li><a href="{{ path('home') }}">Editions</a> <span class="divider">/</span></li>
    <li><a href="{{ path('edition_show', { 'slug': entity.slug }) }}">{{ entity.name }}</a> <span class="divider">/</span></li>
    <li class="active">Edit</li>
{% endblock %}

{% block javascript %}
<script>
    jQuery(".tagManager").tagsManager(
        {
            CapitalizeFirstLetter: true,
            preventSubmitOnEnter: true,
            prefilled: [{% for tag in entity.tags %}{% if not loop.first %}, {% endif %}"{{ tag.name }}"{% endfor %}],
            typeahead: true,
            typeaheadAjaxPolling: true,
            typeaheadAjaxSource: '/tags/pull',
            AjaxPush: '/tags/push',
        }
    );

    if($("#editionista_websitebundle_editiontype_licenseType").val() !== 'other') {
        $("#editionista_websitebundle_editiontype_license").hide();
    }

    $('#editionista_websitebundle_editiontype_licenseType').on(
    'change',
        function() {
            if(this.value === 'other') {
                $('#editionista_websitebundle_editiontype_license').show();

            } else {
                $("#editionista_websitebundle_editiontype_license").hide();
            }
        }
    );
</script>
{% endblock %}

{% block content %}
    {% form_theme form with '::form.html.twig' %}
    
<div class="row-fluid">
    <div class="span12">
        <h1>Edit <span class="muted">&ldquo;</span> {{ entity.name }} <span class="muted">&rdquo;</span></h1>
        <p>
             <small>Last update to the repository: {% if entity.updatedRepositoryAt is not null %}{{ time_diff(entity.updatedRepositoryAt) }}{% else %}Unknown{% endif %}</small>
        </p>
    </div>
</div>
<form class="form-horizontal" action="{{ path('edition_update', { 'slug': entity.slug }) }}" method="post" {{ form_enctype(form) }}>
<div class="row-fluid space">
    <div class="span3">
        <legend>General Information</legend>
        <p>
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
        </p>
        <p>
            {{ form_label(form.homepage) }}
            {{ form_widget(form.homepage) }}
        </p>
        <p>
            {{ form_label(form.version) }}
            {{ form_widget(form.version) }}
        </p>
        <p>
            {{ form_label(form.reference) }}
            {{ form_widget(form.reference) }}
        </p>
    </div>
    <div class="span3">
        <legend>Tags</legend>
            <label for="tags">Tags</label>
            <p><input type="text" name="tags" placeholder="Tags" class="tagManager"/></p>
    </div>
    <div class="span6">
        <legend>Description</legend>
        {{ form_widget(form.description) }}
    </div>
</div>
<div class="row-fluid space">
    <div class="span6">
        <legend>Readme</legend>
        <p>{{ form_widget(form.readme) }}</p>
    </div>
    <div class="span6">
        <legend>License</legend>        
        <p>{{ form_widget(form.licenseType) }}</p>
        <p>{{ form_widget(form.license) }}</p>
    </div>
</div>
<div class="row-fluid space">
    <div class="span1">
        {{ form_widget(form) }}
            
        <p>
            <button type="submit" class="btn"><i class="icon-ok"></i> Edit</button>
        </p>
        </form>
    </div>
    <div class="span2">
        <p>
            <a href="{{ path('edition_delete', { 'slug': entity.slug }) }}" class="btn btn-danger"><i class="icon-trash"></i> Delete</a>
        </p>
    </div>
</div>



{% endblock %}

src/Editionista/WebsiteBundle/Resources/views/Edition/index.html.twig
{% extends "EditionistaWebsiteBundle::layout.html.twig" %}

{% import "EditionistaWebsiteBundle::macros.html.twig" as macros %}

{% block alert %}
{% endblock %}

{% block breadcrumbs %}
    <li class="active"><i class="icon-home"></i> Home</li>
{% endblock %}

{% block content %}
<div class="row-fluid space">
    <div class="span12">
        <h1>Editionista</h1>
        <p>Enjoy Symfony2 in every flavour!</p>
    </div>
</div>
<div class="row-fluid space">
    <div class="span4">
        <h3>What?</h3>
        <div class="span3">
            <i class="icon-cogs icon-4x icon-muted pull-left"></i>
        </div>
        <div class="span8">
            Editionista is a community driven hub for <a href="http://symfony.com/distributions">Symfony2 Distributions</a>. You can <a href="{{ path('edition_add_list') }}">add your own</a> or browse existing ones.
       </div>
    </div>
    <div class="span4">
        <h3>Why?</h3>
        <div class="span3">
            <i class="icon-heart icon-4x icon-muted pull-left"></i>
        </div>
        <div class="span8">
            Distributions offer reusable and still flexible starting points for your projects. Editionista aims to complement the <a href="http://symfony.com/download">official</a> Distributions with community additions. 
       </div>
    </div>
    <div class="span4">
        <h3>Who?</h3>
        <div class="span3">
            <i class="icon-group icon-4x icon-muted pull-left"></i>
        </div>
        <div class="span8">
            Patched together during a short weekend Editionista still lacks content and most features. Feedback and <a href="http://github.com/fabstei/editionista">contributions</a> are most welcome!
       </div>
    </div>
</div>
{{ macros.Editions(entities) }}
{% endblock %}

src/Editionista/WebsiteBundle/Resources/views/Edition/show.html.twig
{% extends "EditionistaWebsiteBundle::layout.html.twig" %}

{% block breadcrumbs %}
    <li><a href="{{ path('home') }}"><i class="icon-home"></i> Home</a> <span class="divider">/</span></li>
    <li><a href="{{ path('home') }}">Editions</a> <span class="divider">/</span></li>
    <li class="active">{{ entity.name }}</li>
{% endblock %}

{% block content %}
<div class="row-fluid space">
    <div class="span12">
        <h1>{{ entity.name }}
            {% if is_granted('EDIT', entity) %}
                <a href="{{ path('edition_edit', { 'slug': entity.slug }) }}"><i class="icon-wrench icon-muted icon-muted-hover" data-placement="top" rel="tooltip" data-original-title="Edit"></i></a>
            {% endif %}
            <a href="https://github.com/{{ entity.vendor }}/{{ entity.editionName }}/archive/master.zip"><i class="icon-download icon-muted icon-muted-hover" data-placement="top" rel="tooltip" data-original-title="Download Edition as .zip"></i></a>
        </h1>
        <h2>
            <small>Contributed by 
               {%- for user in entity.users -%}
                    {% if not loop.first %}, {% endif %}
                    <a href="{{ path('user_profile', { 'name': user.username }) }}">{{ user.username }}</a>
               {%- endfor -%}
            </small>
        </h2>
        <div class="row-fluid">
            <div class="span4">
                <p><small>Symfony2 version used: {{ entity.version }}{% if entity.reference is not null %} <span class="muted">({{ entity.reference }})</span>{% endif %}</small></p>
                <p><small>Git clone url: <a href="https://github.com/{{ entity.vendor }}/{{ entity.editionName }}">https://github.com/{{ entity.vendor }}/{{ entity.editionName }}</a></small></p>
                {% if entity.homepage is not null %}<p><small>Homepage: <a href="{{ entity.homepage }}">{{ entity.homepage }}</a></small></p>{% endif %}
            </div>
            <div class="span4">
                <p><small>Last repository update: {{ time_diff(entity.updatedRepositoryAt) }}</small></p>
                <p>
                    <small>Tags: 
                        {%- for tag in entity.tags -%}
                            {% if not loop.first %}, {% endif %}
                            {{ tag.name }}
                        {%- endfor -%}
                    </small>
                </p>
            </div>
            <div class="span4">
                {% if 'other' not in entity.licenseType %}
                    <p><small>License: {{ entity.licenseType|capitalize }}</small></p>
                {% endif %}
                {% if entity.travis is not null %}
                    <p><a href="https://travis-ci.org/{{ entity.vendor }}/{{ entity.editionName }}"><img src="https://travis-ci.org/{{ entity.vendor }}/{{ entity.editionName }}.png" /></a></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row-fluid space">
    <div class="span12 well">
        <p>{{ entity.description }}</p>
    </div>
</div>
<div class="row-fluid space">
    <div class="span12">
        <ul class="nav nav-tabs" id="tabs">
            {% if entity.readme is not null %}<li class="active"><a href="#readme">Readme</a></li>{% endif %}
            {% if entity.license is not null and 'other' in entity.licenseType %}<li{% if entity.readme is null %} class="active"{% endif %}><a href="#license">License</a></li>{% endif %}
        </ul>
        
        <div class="tab-content well">
            {% if entity.readme is not null %}<div class="tab-pane active" id="readme">{{ entity.readme  | format_text('markdown') | raw }}</div>{% endif %}
            {% if entity.license is not null and 'other' in entity.licenseType %}<div class="tab-pane {% if entity.readme is not null %}fade{% else %}active{% endif %}" id="license">{{ entity.license }}</div>{% endif %}
        </div>
    </div>
</div>
    
{% endblock %}